### ISSUE TITLE
Bulk Device Wipe of Android

### ISSUE THREAD

**Issue by IanStretton** [MrTechGadget/aw-bulkdevices-script#9]
Hi Mr TechGadget,
Firstly thank you for creating these scripts they have  proved very helpful in a process/project I am doing.
I have a question i hope you can help me with.
When we perform the Reset-FullDevice.ps1 on iOS devices it works perfectly.  When we run this on Android it errors with code 400, bad request.
We think this is because we need to perform the Reset-EnterpriseWipe.ps1 against the Android instead, but when we try to run this we get an Error 500 against all the Android devices. Could you give us help as to why this might be ?
When we perform the device wipe on an Android from within the AirWatch console, it works, but it does ask us first 2 questions, 1) is which storage do we also want to wipe and 2) the PIN number to allow the wipe. when we do it manually for iOS we don't get asked those questions.
Is this what is causing the issue, do we need to pass more information to the API to force the wipe on Androids ?

Any help or guidance you can provide as soon as you can, would be great.
Thanks

**Comment by MrTechGadget** [comment]
I’m on holiday currently but will look into this as soon as I can. Should be a pretty easy fix I think.

**Comment by MrTechGadget** [comment]
Ian, are these Android Enterprise or Legacy devices, or both?

**Comment by MrTechGadget** [comment]
From the API docs:

> 5xx:Server Error - Indicates that there was a problem on the server side
> 500 "Internal Server Error"
> This indicates an error with the API. A 500 error response is the generic API error response that is returned whenever it encounters an exception.

Makes me wonder about your environment, what version of Workspace ONE UEM / AirWatch are you running this on? Hosted or on-prem? (Wondering what logs might be available to review)

**Comment by IanStretton** [comment]
We are using hosted UEM, Version: 19.10.0.5 (1910) Build Information: AIRW-AWCREL49-30 
692613ac2416f5d2a84069d8b48de0277d31aaf6 

For the errors, in a way yes i guess we are saying there is 2 issues, but we believe the important one is the error 500 on the EnterpriseWipe for Androids.

If there are any logs you could suggest to look at that would be great as well.

**Comment by MrTechGadget** [comment]
Ok good, same as I am on, so I should be able to reproduce the issue.

**Comment by MrTechGadget** [comment]
> 
> For the errors, in a way yes i guess we are saying there is 2 issues, but we believe the important one is the error 500 on the EnterpriseWipe for Androids.
> 

Ok, from the looks of it, they have added in a new poorly documented required field to this version 1 API (without adding a version, very poor API management VMware, if you are reading this!)

![IMG_0074](https://user-images.githubusercontent.com/17124213/69768876-6e12c080-1150-11ea-972e-7fe244f588d5.jpeg)

I’ll have to either figure out the XMLmodel they are requiring or find a different way of doing this.

Anyway, just wanted to give an update.

**Comment by MrTechGadget** [comment]
Ok, I get the same error on EnterpriseWipe, which looks like a VMware issue. I’ll submit a support ticket for them to investigate, recommend you do the same if you can. The request formatting should work fine. 

![IMG_0075](https://user-images.githubusercontent.com/17124213/69770603-a4a00980-1157-11ea-9c5f-9e5fb9c04522.jpeg)

The same call to a slightly different API (using the device ID instead of serial) works fine, so I think this is a problem with this API, not my script.

That is for the EntepriseWipe issue. I’ve still got to look at the other one for FullWipe.

**Comment by IanStretton** [comment]
thanks for looking at this, we will do what we can to log a ticket as well.

if there is any information we can provide you to help troubleshoot, let us know.

**Comment by IanStretton** [comment]
Hi, any news on the bug with VMWare.  They aren't responding to us at all, have you had any joy ?

**Comment by MrTechGadget** [comment]
Whatever the issue was last week, my script is working correctly now for me for Enterprise Wipe of Android.

.\Reset-EnterpriseWipe.ps1 -file .\Serials.csv -fileColumn SerialNumber

This is what my CSV looks like

SerialNumber
abcd1234

Please retest and let me know.

I still need to take a look at Rest-FullDevice.ps1 for the error 400.

**Comment by MrTechGadget** [comment]
I believe e0881ba fixes the full device wipe for Android. Please let me know if that is not the case. 

The enterprise wipe is working fine for me now as well.

Let me know if your results differ. Thanks!
